export const countries = [
  {
    value: 1, viewValue: 'Afghanistan'
  },
  {
    value: 2,
    viewValue: 'Albania'
  },
  {value: 3, viewValue: 'Algeria'},
  {value: 4, viewValue: 'Andorra'},
  {value: 5, viewValue: 'Angola'},
  {value: 6, viewValue: 'Antigua and Barbuda'},
  {value: 7, viewValue: 'Argentina'},
  {value: 8, viewValue: 'Armenia'},
  {value: 9, viewValue: 'Australia'},
  {value: 10, viewValue: 'Austria'},
  {value: 11, viewValue: 'Azerbaijan'},
  {value: 12, viewValue: 'Bahamas'},
  {value: 13, viewValue: 'Bahrain'},
  {value: 14, viewValue: 'Bangladesh'},
  {value: 15, viewValue: 'Barbados'},
  {value: 16, viewValue: 'Belarus'},
  {value: 17, viewValue: 'Belgium'},
  {value: 18, viewValue: 'Belize'},
  {value: 19, viewValue: 'Benin'},
  {value: 20, viewValue: 'Bhutan'},
  {value: 21, viewValue: 'Bolivia'},
  {value: 22, viewValue: 'Bosnia and Herzegovina'},
  {value: 23, viewValue: 'Botswana'},
  {value: 24, viewValue: 'Brazil'},
  {value: 25, viewValue: 'Brunei'},
  {value: 26, viewValue: 'Bulgaria'},
  {value: 27, viewValue: 'Burkina Faso'},
  {value: 28, viewValue: 'Burundi'},
  {value: 29, viewValue: 'Cabo Verde'},
  {value: 30, viewValue: 'Cambodia'},
  {value: 31, viewValue: 'Cameroon'},
  {value: 32, viewValue: 'Canada'},
  {value: 33, viewValue: 'Central African Republic'},
  {value: 34, viewValue: 'Chad'},
  {value: 35, viewValue: 'Chile'},
  {value: 36, viewValue: 'China'},
  {value: 37, viewValue: 'Colombia'},
  {value: 38, viewValue: 'Comoros'},
  {value: 39, viewValue: 'Congo, Democratic Republic of the'},
  {value: 40, viewValue: 'Congo, Republic of the'},
  {value: 41, viewValue: 'Costa Rica'},
  {value: 42, viewValue: 'Croatia'},
  {value: 43, viewValue: 'Cuba'},
  {value: 44, viewValue: 'Cyprus'},
  {value: 45, viewValue: 'Czech Republic'},
  {value: 46, viewValue: 'Denmark'},
  {value: 47, viewValue: 'Djibouti'},
  {value: 48, viewValue: 'Dominica'},
  {value: 49, viewValue: 'Dominican Republic'},
  {value: 50, viewValue: 'East Timor'},
  {value: 51, viewValue: 'Ecuador'},
  {value: 52, viewValue: 'Egypt'},
  {value: 53, viewValue: 'El Salvador'},
  {value: 54, viewValue: 'Equatorial Guinea'},
  {value: 55, viewValue: 'Eritrea'},
  {value: 56, viewValue: 'Estonia'},
  {value: 57, viewValue: 'Eswatini'},
  {value: 58, viewValue: 'Ethiopia'},
  {value: 59, viewValue: 'Fiji'},
  {value: 60, viewValue: 'Finland'},
  {value: 61, viewValue: 'France'},
  {value: 62, viewValue: 'Gabon'},
  {value: 63, viewValue: 'Gambia'},
  {value: 64, viewValue: 'Georgia'},
  {value: 65, viewValue: 'Germany'},
  {value: 66, viewValue: 'Ghana'},
  {value: 67, viewValue: 'Greece'},
  {value: 68, viewValue: 'Grenada'},
  {value: 69, viewValue: 'Guatemala'},
  {value: 70, viewValue: 'Guinea'},
  {value: 71, viewValue: 'Guinea-Bissau'},
  {value: 72, viewValue: 'Guyana'},
  {value: 73, viewValue: 'Haiti'},
  {value: 74, viewValue: 'Honduras'},
  {value: 75, viewValue: 'Hungary'},
  {value: 76, viewValue: 'Iceland'},
  {value: 77, viewValue: 'India'},
  {value: 78, viewValue: 'Indonesia'},
  {value: 79, viewValue: 'Iran'},
  {value: 80, viewValue: 'Iraq'},
  {value: 81, viewValue: 'Ireland'},
  {value: 82, viewValue: 'Israel'},
  {value: 83, viewValue: 'Italy'},
  {value: 84, viewValue: 'Jamaica'},
  {value: 85, viewValue: 'Japan'},
  {value: 86, viewValue: 'Jordan'},
  {value: 87, viewValue: 'Kazakhstan'},
  {value: 88, viewValue: 'Kenya'},
  {value: 89, viewValue: 'Kiribati'},
  {value: 90, viewValue: 'Korea, North'},
  {value: 91, viewValue: 'Korea, South'},
  {value: 92, viewValue: 'Kuwait'},
  {value: 93, viewValue: 'Kyrgyzstan'},
  {value: 94, viewValue: 'Laos'},
  {value: 95, viewValue: 'Latvia'},
  {value: 96, viewValue: 'Lebanon'},
  {value: 97, viewValue: 'Lesotho'},
  {value: 98, viewValue: 'Liberia'},
  {value: 99, viewValue: 'Libya'},
  {value: 100, viewValue: 'Liechtenstein'},
  {value: 101, viewValue: 'Lithuania'},
  {value: 102, viewValue: 'Luxembourg'},
  {value: 103, viewValue: 'Madagascar'},
  {value: 104, viewValue: 'Malawi'},
  {value: 105, viewValue: 'Malaysia'},
  {value: 106, viewValue: 'Maldives'},
  {value: 107, viewValue: 'Mali'},
  {value: 108, viewValue: 'Malta'},
  {value: 109, viewValue: 'Marshall Islands'},
  {value: 110, viewValue: 'Mauritania'},
  {value: 111, viewValue: 'Mauritius'},
  {value: 112, viewValue: 'Mexico'},
  {value: 113, viewValue: 'Micronesia'},
  {value: 114, viewValue: 'Moldova'},
  {value: 115, viewValue: 'Monaco'},
  {value: 116, viewValue: 'Mongolia'},
  {value: 117, viewValue: 'Montenegro'},
  {value: 118, viewValue: 'Morocco'},
  {value: 119, viewValue: 'Mozambique'},
  {value: 120, viewValue: 'Myanmar'},
  {value: 121, viewValue: 'Namibia'},
  {value: 122, viewValue: 'Nauru'},
  {value: 123, viewValue: 'Nepal'},
  {value: 124, viewValue: 'Netherlands'},
  {value: 125, viewValue: 'New Zealand'},
  {value: 126, viewValue: 'Nicaragua'},
  {value: 127, viewValue: 'Niger'},
  {value: 128, viewValue: 'Nigeria'},
  {value: 129, viewValue: 'North Macedonia'},
  {value: 130, viewValue: 'Norway'},
  {value: 131, viewValue: 'Oman'},
  {value: 132, viewValue: 'Pakistan'},
  {value: 133, viewValue: 'Palau'},
  {value: 134, viewValue: 'Panama'},
  {value: 135, viewValue: 'Papua New Guinea'},
  {value: 136, viewValue: 'Paraguay'},
  {value: 137, viewValue: 'Peru'},
  {value: 138, viewValue: 'Philippines'},
  {value: 139, viewValue: 'Poland'},
  {value: 140, viewValue: 'Portugal'},
  {value: 141, viewValue: 'Qatar'},
  {value: 142, viewValue: 'Romania'},
  {value: 143, viewValue: 'Russia'},
  {value: 144, viewValue: 'Rwanda'},
  {value: 145, viewValue: 'Saint Kitts and Nevis'},
  {value: 146, viewValue: 'Saint Lucia'},
  {value: 147, viewValue: 'Saint Vincent and the Grenadines'},
  {value: 148, viewValue: 'Samoa'},
  {value: 149, viewValue: 'San Marino'},
  {value: 150, viewValue: 'Sao Tome and Principe'},
  {value: 151, viewValue: 'Saudi Arabia'},
  {value: 152, viewValue: 'Senegal'},
  {value: 153, viewValue: 'Serbia'},
  {value: 154, viewValue: 'Seychelles'},
  {value: 155, viewValue: 'Sierra Leone'},
  {value: 156, viewValue: 'Singapore'},
  {value: 157, viewValue: 'Slovakia'},
  {value: 158, viewValue: 'Slovenia'},
  {value: 159, viewValue: 'Solomon Islands'},
  {value: 160, viewValue: 'Somalia'},
  {value: 161, viewValue: 'South Africa'},
  {value: 162, viewValue: 'South Sudan'},
  {value: 163, viewValue: 'Spain'},
  {value: 164, viewValue: 'Sri Lanka'},
  {value: 165, viewValue: 'Sudan'},
  {value: 166, viewValue: 'Suriname'},
  {value: 167, viewValue: 'Sweden'},
  {value: 168, viewValue: 'Switzerland'},
  {value: 169, viewValue: 'Syria'},
  {value: 170, viewValue: 'Taiwan'},
  {value: 171, viewValue: 'Tajikistan'},
  {value: 172, viewValue: 'Tanzania'},
  {value: 173, viewValue: 'Thailand'},
  {value: 174, viewValue: 'Togo'},
  {value: 175, viewValue: 'Tonga'},
  {value: 176, viewValue: 'Trinidad and Tobago'},
  {value: 177, viewValue: 'Tunisia'},
  {value: 178, viewValue: 'Turkey'},
  {value: 179, viewValue: 'Turkmenistan'},
  {value: 180, viewValue: 'Tuvalu'},
  {value: 181, viewValue: 'Uganda'},
  {value: 182, viewValue: 'Ukraine'},
  {value: 183, viewValue: 'United Arab Emirates'},
  {value: 184, viewValue: 'United Kingdom'},
  {value: 185, viewValue: 'United States'},
  {value: 186, viewValue: 'Uruguay'},
  {value: 187, viewValue: 'Uzbekistan'},
  {value: 188, viewValue: 'Vanuatu'},
  {value: 189, viewValue: 'Vatican City'},
  {value: 190, viewValue: 'Venezuela'},
  {value: 191, viewValue: 'Vietnam'},
  {value: 192, viewValue: 'Yemen'},
  {value: 193, viewValue: 'Zambia'},
  {value: 194, viewValue: 'Zimbabwe'}
];
